import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';
import { styles } from './styles.css';

const notoSans = localFont({
  src: '../assets/fonts/NotoSansKRVF.woff2',
  variable: '--font-noto-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} ${styles.body}`}>{children}</body>
    </html>
  );
}
